import type { Order } from './orders.types';

export const INITIAL_ORDERS: Order[] = [
    /* ── Active delivery arc ─────────────────────────────────── */
    {
        id: "#ORD-8821",
        customer: "Priya Sharma",
        phone: "+91 98201 34567",
        items: [
            { name: "Chicken Biryani", qty: 2, price: 299 },
            { name: "Raita", qty: 1, price: 49 },
            { name: "Coke", qty: 2, price: 50 },
        ],
        total: 747,
        address: "14B, Marine Lines, Mumbai 400002",
        placedAt: "2 min ago",
        eta: "30 min",
        status: "new",
        driver: null,
        driverPhone: null,
        paymentMode: "Prepaid",
        specialNote: "Extra spicy please, no onions in raita",
    },
    {
        id: "#ORD-8820",
        customer: "Rahul Mehta",
        phone: "+91 90004 12233",
        items: [
            { name: "Paneer Tikka", qty: 1, price: 320 },
            { name: "Butter Naan", qty: 3, price: 45 },
            { name: "Lassi", qty: 2, price: 90 },
        ],
        total: 635,
        address: "7, Bandra West, Mumbai 400050",
        placedAt: "11 min ago",
        eta: "20 min",
        status: "preparing",
        driver: null,
        driverPhone: null,
        paymentMode: "Prepaid",
    },
    {
        id: "#ORD-8819",
        customer: "Anika Joshi",
        phone: "+91 87652 09871",
        items: [
            { name: "Dal Makhani", qty: 2, price: 240 },
            { name: "Jeera Rice", qty: 2, price: 160 },
        ],
        total: 800,
        address: "22, Andheri East, Mumbai 400069",
        placedAt: "22 min ago",
        eta: "5 min",
        status: "ready",
        driver: null,
        driverPhone: null,
        paymentMode: "COD",
    },
    {
        id: "#ORD-8818",
        customer: "Dev Kapoor",
        phone: "+91 99887 65432",
        items: [
            { name: "Mutton Rogan Josh", qty: 1, price: 420 },
            { name: "Garlic Naan", qty: 4, price: 55 },
        ],
        total: 640,
        address: "3, Powai, Mumbai 400076",
        placedAt: "35 min ago",
        eta: "10 min",
        status: "driver_assigned",
        driver: "Suresh Kumar",
        driverPhone: "+91 91234 56789",
        paymentMode: "Prepaid",
    },
    {
        id: "#ORD-8817",
        customer: "Sneha Iyer",
        phone: "+91 77889 90001",
        items: [{ name: "Veg Thali", qty: 3, price: 350 }],
        total: 1050,
        address: "55, Dadar, Mumbai 400014",
        placedAt: "50 min ago",
        eta: "Delivered",
        status: "picked_up",
        driver: "Mohan Rao",
        driverPhone: "+91 99001 23456",
        paymentMode: "Prepaid",
    },
    {
        id: "#ORD-8816",
        customer: "Vikram Singh",
        phone: "+91 88001 23456",
        items: [
            { name: "Fish Curry", qty: 1, price: 380 },
            { name: "Steamed Rice", qty: 2, price: 130 },
        ],
        total: 640,
        address: "9, Malad West, Mumbai 400064",
        placedAt: "1h 10min ago",
        eta: "Delivered",
        status: "delivered",
        driver: "Ramesh Patil",
        driverPhone: "+91 88765 43210",
        paymentMode: "COD",
    },

    /* ── Cancellation / refund arc (demo scenarios) ──────────── */

    // Scenario A: Prepaid, cancelled while rider had food → returning
    {
        id: "#ORD-8815",
        customer: "Ritu Verma",
        phone: "+91 93001 77654",
        items: [
            { name: "Butter Chicken", qty: 2, price: 360 },
            { name: "Butter Naan", qty: 4, price: 45 },
        ],
        total: 900,
        address: "12, Santacruz West, Mumbai 400054",
        placedAt: "42 min ago",
        eta: "Returning",
        status: "cancelled_returning",
        driver: "Arjun Nair",
        driverPhone: "+91 90099 12345",
        paymentMode: "Prepaid",
        cancelledFrom: "picked_up",
        cancelledBy: "customer",
    },

    // Scenario B: Prepaid, food returned, waiting to process refund
    {
        id: "#ORD-8814",
        customer: "Karan Malhotra",
        phone: "+91 87001 44321",
        items: [{ name: "Chicken Biryani", qty: 1, price: 299 }],
        total: 299,
        address: "8, Goregaon East, Mumbai 400063",
        placedAt: "1h 28min ago",
        eta: "Returned",
        status: "return_received",
        driver: "Deepak Sharma",
        driverPhone: "+91 96543 21098",
        paymentMode: "Prepaid",
        cancelledFrom: "picked_up",
        cancelledBy: "customer",
    },

    // Scenario C: Prepaid, refund initiated
    {
        id: "#ORD-8813",
        customer: "Neha Gupta",
        phone: "+91 91001 22334",
        items: [
            { name: "Paneer Butter Masala", qty: 1, price: 300 },
            { name: "Garlic Naan", qty: 2, price: 55 },
        ],
        total: 410,
        address: "5, Bhandup West, Mumbai 400078",
        placedAt: "2h 5min ago",
        eta: "Refund pending",
        status: "refund_processing",
        driver: null,
        driverPhone: null,
        paymentMode: "Prepaid",
        cancelledFrom: "picked_up",
        cancelledBy: "customer",
    },

    // Scenario D: Cancelled before pickup, prepaid → auto-refund, no return
    {
        id: "#ORD-8812",
        customer: "Sanjay Patil",
        phone: "+91 98501 66789",
        items: [{ name: "Veg Biryani", qty: 2, price: 220 }],
        total: 440,
        address: "3, Kurla West, Mumbai 400070",
        placedAt: "55 min ago",
        eta: "N/A",
        status: "cancelled",
        driver: null,
        driverPhone: null,
        paymentMode: "Prepaid",
        cancelledFrom: "preparing",
        cancelledBy: "customer",
    },

    // Scenario E: COD cancelled → no refund
    {
        id: "#ORD-8811",
        customer: "Lakshmi Nair",
        phone: "+91 88901 55678",
        items: [{ name: "Dal Makhani", qty: 1, price: 240 }],
        total: 240,
        address: "19, Chembur, Mumbai 400071",
        placedAt: "1h 12min ago",
        eta: "N/A",
        status: "cancelled",
        driver: null,
        driverPhone: null,
        paymentMode: "COD",
        cancelledFrom: "preparing",
        cancelledBy: "customer",
    },
];